// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"
)

// MerchantRepository is an autogenerated mock type for the MerchantRepository type
type MerchantRepository struct {
	mock.Mock
}

// GetIDByApiKey provides a mock function with given fields: ctx, apikey
func (_m *MerchantRepository) GetIDByApiKey(ctx context.Context, apikey uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, apikey)

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, apikey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, apikey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
