# Start from golang base image
FROM golang:1.16-alpine3.13

# Add Maintainer info
LABEL maintainer="overridesh"

# Update Alpine
RUN apk update

# Install utils packages.
RUN apk add --no-cache git

# Set the current working directory inside the container
WORKDIR /go/src/github.com/overridesh/checkout-challenger

# Copy go mod and sum files
COPY go.mod .
COPY go.sum .
COPY scripts scripts

# Download all dependencies. Dependencies will be cached if the go.mod and the go.sum files are not changed
RUN go mod download

RUN go get github.com/canthefason/go-watcher/cmd/watcher

WORKDIR /go/src/github.com/overridesh/checkout-challenger/cmd/grpc

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

ENTRYPOINT ["watcher", "-watch", "github.com/overridesh/checkout-challenger"] 